[package]
name = "rust-playground"
version = "0.1.0"
authors = ["Andres Senac <asenac@nuodb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "7.0.0"